# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Usually Pragmatic
email: <redacted> 
description: Just a <a href="https://tomcritchlow.com/2019/02/17/building-digital-garden/">digital garden</a> of my own.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://michaelwoods.io" # the base hostname & protocol for your site, e.g. http://example.com
minima:
    social_links:
        twitter: carpdiem
        github: carpdiem

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

feed:
    categories:
        - blog
        - essays
        - lists
        - misc
        - projects

collections:
        projects:
                output: true
                sort_by: last_modified
        lists:
                output: true
                sort_by: last_modified
        essays:
                output: true
                sort_by: last_modified
        blog:
                output: true
                sort_by: last_modified
        misc:
                output: true
                sort_by: last_modified

header_pages:
    - blog.md
    - essays.md
    - lists.md
    - misc.md
    - projects.md
    - about.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
