name: proselint

on: [push, pull_request]

jobs:
    proselint:
        runs-on: ubuntu-latest

        steps:
        - name: pull_repo
          uses: actions/checkout@v2

        - name: set up python
          uses: actions/setup-python@v1
          
        - name: install_proselint
          run: |
            python -m pip install --upgrade pip
            pip install proselint

        - name: run_proselint
          run: find . -name '*.markdown' -exec proselint {} + || exit
