# This is a basic workflow to help you get started with Actions

name: shell_check

# Controls when the action will run. Triggers the workflow on push or pull request
# events 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  shell_check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a set of commands using the runners shell
    - name: pull_repo
    # Need to include checkout action to have access to current repo
      uses: actions/checkout@v2

    - name: run_shellcheck
      run: ls
